import { randomUUID } from 'node:crypto';
import type { Request, Response } from 'express';
import { ProjectModel } from '../models/project.model.js';
import { ForbiddenError, NotFoundError, ValidationError } from '../utils/errors.js';

function param(req: Request, name: string): string { const value = req.params[name]; if (typeof value !== 'string') throw new NotFoundError(); return value; }
function project(req: Request) { const p = ProjectModel.find(param(req, 'projectId'), req.user!.id); if (!p) throw new NotFoundError('Proyecto'); return p; }
function parentIsValid(projectId: string, folderId: string, parentId: string | null | undefined): void {
  if (!parentId) return;
  if (folderId === parentId) throw new ValidationError('Una carpeta no puede ser su propia padre');
  let cursor = ProjectModel.folder(parentId, projectId);
  if (!cursor) throw new ValidationError('Carpeta padre no encontrada');
  while (cursor.parent_id) { if (cursor.parent_id === folderId) throw new ValidationError('El movimiento crearía un ciclo'); cursor = ProjectModel.folder(cursor.parent_id, projectId)!; }
}
export async function listProjects(req: Request, res: Response): Promise<void> { res.json({ projects: ProjectModel.list(req.user!.id, req.query.archived === 'true') }); }
export async function createProject(req: Request, res: Response): Promise<void> { const name = (req.validatedBody as { name: string }).name; const p = ProjectModel.create({ id: randomUUID(), userId: req.user!.id, name, mainSessionId: randomUUID() }); res.status(201).json({ project: p, mainSessionId: p.main_session_id }); }
export async function getProjectTree(req: Request, res: Response): Promise<void> { const p = project(req); const folderId = typeof req.query.folderId === 'string' ? req.query.folderId : null; if (folderId && !ProjectModel.folder(folderId, p.id)) throw new NotFoundError('Carpeta'); const folders = ProjectModel.folders(p.id); const directFolders = folders.filter(f => f.parent_id === folderId); const breadcrumbs = []; let cursor = folderId ? ProjectModel.folder(folderId, p.id) : undefined; while (cursor) { breadcrumbs.unshift({ id: cursor.id, name: cursor.name }); cursor = cursor.parent_id ? ProjectModel.folder(cursor.parent_id, p.id) : undefined; } res.json({ project: p, folder: folderId ? ProjectModel.folder(folderId, p.id) : null, breadcrumbs, folders: directFolders, sessions: ProjectModel.sessions(p.id, folderId) }); }
export async function activateProject(req: Request, res: Response): Promise<void> { const p = ProjectModel.activate(param(req, 'projectId'), req.user!.id); if (!p) throw new NotFoundError('Proyecto'); res.json({ project: p }); }
export async function archiveProject(req: Request, res: Response): Promise<void> { project(req); ProjectModel.archive(param(req, 'projectId'), req.user!.id); res.json({ success: true }); }
export async function renameProject(req: Request, res: Response): Promise<void> { project(req); ProjectModel.rename(param(req, 'projectId'), req.user!.id, (req.validatedBody as { name: string }).name); res.json({ project: project(req) }); }
export async function createFolder(req: Request, res: Response): Promise<void> { const p = project(req); const b = req.validatedBody as any; parentIsValid(p.id, '', b.parentId); if (b.kind === 'important' && b.isContentFolder) throw new ValidationError('La carpeta importante no es carpeta de contenido'); const folder = ProjectModel.createFolder({ id: randomUUID(), projectId: p.id, parentId: b.parentId ?? null, name: b.name, kind: b.kind, isContentFolder: b.isContentFolder, resourceScope: b.isContentFolder ? b.resourceScope : null }); res.status(201).json({ folder }); }
export async function updateFolder(req: Request, res: Response): Promise<void> { const p = project(req); const current = ProjectModel.folder(param(req, 'folderId'), p.id); if (!current) throw new NotFoundError('Carpeta'); const b = req.validatedBody as any; parentIsValid(p.id, current.id, b.parentId); if (current.kind === 'important' && b.isContentFolder) throw new ValidationError('La carpeta importante no es carpeta de contenido'); ProjectModel.updateFolder(current.id, p.id, b); res.json({ folder: ProjectModel.folder(current.id, p.id) }); }
export async function deleteFolder(req: Request, res: Response): Promise<void> { const p = project(req); const f = ProjectModel.folder(param(req, 'folderId'), p.id); if (!f) throw new NotFoundError('Carpeta'); if (f.kind === 'important') throw new ForbiddenError('La carpeta importante no se puede eliminar'); ProjectModel.deleteFolder(f.id, p.id); res.json({ success: true }); }
export async function moveSession(req: Request, res: Response): Promise<void> { const p = project(req); const { folderId } = req.validatedBody as { folderId: string }; const f = ProjectModel.folder(folderId, p.id); if (!f?.is_content_folder) throw new ValidationError('El destino debe ser una carpeta de contenido'); if (!ProjectModel.moveSession(param(req, 'sessionId'), p.id, folderId)) throw new ForbiddenError('No se puede mover esta sesión'); res.json({ success: true }); }
